# Generated by Django 5.1.6 on 2025-02-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pd1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='comapany_name',
            new_name='company_name',
        ),
    ]
