# Generated by Django 5.1.6 on 2025-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd1', '0004_rename_job_role_apply_city_apply_email_apply_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.BinaryField(),
        ),
    ]
