# Generated by Django 5.1.6 on 2025-02-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd1', '0005_alter_apply_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
