# Generated by Django 5.1.6 on 2025-02-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd1', '0006_alter_apply_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
