# Generated by Django 5.1.6 on 2025-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd1', '0008_userjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='email',
            field=models.CharField(default='default@email.com', max_length=200),
        ),
    ]
